#!/usr/bin/env python3

from astral import LocationInfo
import datetime
from astral.sun import sun
import subprocess
import time
import pytz
from typing import Dict

utc=pytz.UTC
current=None

def change_wallpaper(style: str):
    wallpaper_file = "/home/mewtastic/Pictures/Wallpapers"
    file_map: Dict[str, str] = {"night": "night.jpg", "day": "day.jpg"}
    if style in file_map.keys():
        wallpaper_file = f"{wallpaper_file}/{file_map[style]}"
    else:
        wallpaper_file = f"{wallpaper_file}/{file_map['night']}"
    subprocess.run(["/usr/bin/xwallpaper", "--zoom", f"{wallpaper_file}"])

if __name__ == "__main__":
    city = LocationInfo("Portland", "Oregon", "US/Pacific", 45.515, -122.679)
    s = sun(city.observer, date=datetime.datetime.today())
    #available times for sun = sunrise, noon, sunset, dusk
    # so you could go even more specific with wallpapers

    while True:
        if datetime.datetime.now().replace(tzinfo=utc) < s["dusk"]:
            if current != "day":
                change_wallpaper("day")
                current = "day"
        elif datetime.datetime.now().replace(tzinfo=utc) >= s["dusk"]:
            if current != "night":
                change_wallpaper("night")
                current = "night"
        time.sleep(300)
